# Introducción

Uno de los insumos escenciales para el diseño de la política pública y el monitoreo del progreso de la sociedad es la disponibilidad de indicadores confiables. Esto es especialmente relevante para los objetivos de desarrollo sostenible y su pretención de no dejar a nadie atrás. Sin embargo, la mayoría de los indicadores relevantes se construye en base a encuestas, las cuales no siempre son representativas a niveles locales o para grupos específicos de la población.

Las metodologías de estimación de área pequeña (SAE PORpor sus siglas en inglés) presentan un conjunto de métodos que son usados para producir estimadores más precisos cuando los estimadores directos basados en encuestas no son confiables en areas geográficas o dominios de estudio en los cuales los tamaños muestrales son demasiado pequeños, o incluso ausentes, y así entregar estimaciones válidas.

Para producir estos estimadores, en general es necesario incluir bases de datos adicionales, mediante un proceso de modelado estadístico.

Existe una basta tradicion de investigación y publicaciones en este tema, desde libros, hasta la producción de guías de trabajo que entregan directrices para que estos procedimientos puedan ser utilizados por agencias estadísticias nacionales e investigadores interesados en el tema.

El presente documento pretende entregar una visión general del tema, con una perspectiva enfocada en la aplicación y la práctica de estas metodologías. Para esto se presenta un marco de trabajo aplicado que detalla el rol del investigador, el proceso de estimación general y la relación con los distintos stakeholders. Luego se presenta una revisión teórica donde se presentan los modelos lineales mixtos o de multinivel en su aplicación en estimaciones de area pequeña. Finalmente se presentan ejemplos prácticos de estas metodologías.