# Resumen

Las metodologías de estimación de area pequeña buscan aumentar la precisión de las estimaciones de indicadores basados en encuestas cuando los datos no son suficientes para representar de manera confiable territorios o grupos de población donde no se cuenta con información suficiente.

Estos métodos se basan en usar información adicional para "darle más fuerza" a los indicadores directos. Es así que existen principalmente dos familias de métodos, basados en información agregada a nivel de area, o a nivel de unidad. En un contexto de estimación de características de hogares a nivel de comuna, los modelos de area usarán información adicional agregada a nivel de comuna, mientras que los modelos de unidad usarán datos a nivel de hogar.

Se presenta también un marco de trabajo con guias generales de buenas prácticas para estas estimaciones, con un foco en la relación del investigador con los stakeholders.

Además, se revisa a grandes razgos las metodologías estadísticas más usadas, correspondiendo a modelos lineales mixtos o multinivel. Estos presentan la particularidad de poder modelar efectos fijos y aleatorios para distintos niveles de anidamiento o agregación. COn esto disminuye el efecto nocivo de variables omitidas.

Finalmente se mencionan aplicaciones notables de la metodología, con objeto de poner en contexto y alentar una revisión más detallada del tema.